extra:
  search:
    language: 'en, pt'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences

nav:
- Introdução: index.md
- Aula1: aula1.md
- Aula2: aula2.md
- Aula3: aula3.md
- Aula4: aula4.md
- "Exercícios: Linked List": exerc-ll.md

plugins:
  - search

site_name: Estrutura de Dados
site_description: Disciplina de Estrutura de Dados
site_author: Allainclair Flausino dos Santos
site_url: https://allainclair.github.io/disc-ed

theme:
  language: pt
  name: material
